### ISSUE TITLE
Option to open all favourites in a new tab

### ISSUE THREAD

**Issue by ZappoB** [canisbos/TabOptions#4]
Hi,

I really happy I found your Safari extensions!

Do you think it is possible to add the option to open all favourites/bookmarks in a new tab, instead of the aktive one?

Thanks an best regards,
Zappo

**Comment by canisbos** [comment]
Hello,

Alas, no, this is not possible to do using the old extension API. I don't know whether it's possible using the new app extension API, but I don't have any plans to port these extensions to the new API (no time).

All I can suggest is that you get into the habit of holding down the Command key when opening bookmarks or favorites, as this will cause them to open in a new tab.

**Comment by ZappoB** [comment]
Thanks for your quick answer! Sad to hear, that you're giving up your extensions, but I can understand. 

Best wishes,
Zappo
